name: .NET Core for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build:
    environment: AzureC4A8CodeSigning

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          tenant-id: a53834b7-42bc-46a3-b004-369735c3acf9 # c4a8.onmicrosoft.com
          client-id: 97676fd8-6001-4096-be4a-fbed37f1355b # from Entra ID app registration
          allow-no-subscriptions: true
      - name: Update dependencies
        run: scripts/update-dependencies.sh
      - name: Install dependencies
        run: dotnet restore -r win-x64 ScepClient.csproj
      - name: Build
        run: dotnet build -p:Version=1.2.$GITHUB_RUN_NUMBER.500 --configuration Release --no-restore -r win-x64 ScepClient.csproj
      - name: Publish
        run: dotnet publish -p:Version=1.2.$GITHUB_RUN_NUMBER.500 --configuration Release --no-restore -r win-x64 -p:PublishSingleFile=true --no-self-contained ScepClient.csproj
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: scepclient-win-x64
          path: bin/Release/net10.0/win-x64/publish/*